apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaccine-student-service-app
  labels:
    app: vaccine-student-service-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vaccine-student-service-app
  template:
    metadata:
      labels:
        app: vaccine-student-service-app
    spec:
      containers:
        - name: vaccine-student-service-app
          image: bits/vaccine-student-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4801

---
apiVersion: v1
kind: Service
metadata:
  name: vaccine-student-service-svc
spec:
  ports:
    - targetPort: 4801
      port: 4801
  selector:
    app: vaccine-student-service-app